// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sales_performance_api.Infrastructure.Persistence;

#nullable disable

namespace sales_performance_api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260923201152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_name");

                    b.ToTable("categories", "public", t =>
                        {
                            t.HasCheckConstraint("ck_categories_name", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", "public", t =>
                        {
                            t.HasCheckConstraint("ck_customers_company", "btrim(company) <> ''");

                            t.HasCheckConstraint("ck_customers_name", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("initials");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_managers");

                    b.ToTable("managers", "public", t =>
                        {
                            t.HasCheckConstraint("ck_managers_initials", "btrim(initials) <> ''");

                            t.HasCheckConstraint("ck_managers_name", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", "public", t =>
                        {
                            t.HasCheckConstraint("ck_products_name", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(3)")
                        .HasDefaultValue("USD")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sale_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sales");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_customer_id");

                    b.HasIndex("ManagerId", "SaleDate")
                        .HasDatabaseName("ix_sales_manager_id_sale_date");

                    b.HasIndex("SaleDate", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_sales_sale_date_id");

                    b.HasIndex("Status", "SaleDate")
                        .HasDatabaseName("ix_sales_status_sale_date");

                    b.ToTable("sales", "public", t =>
                        {
                            t.HasCheckConstraint("ck_sales_currency", "currency = 'USD'");

                            t.HasCheckConstraint("ck_sales_sale_date", "isfinite(sale_date)");

                            t.HasCheckConstraint("ck_sales_status", "status IN ('Paid', 'Cancelled', 'Refunded')");
                        });
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryIdAtSale")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id_at_sale");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductNameAtSale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name_at_sale");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<decimal>("UnitSalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_sale_price");

                    b.HasKey("Id")
                        .HasName("pk_sale_items");

                    b.HasIndex("CategoryIdAtSale")
                        .HasDatabaseName("ix_sale_items_category_id_at_sale");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_items_product_id");

                    b.HasIndex("SaleId", "LineNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_items_sale_id_line_number");

                    b.ToTable("sale_items", "public", t =>
                        {
                            t.HasCheckConstraint("ck_sale_items_line_number", "line_number > 0");

                            t.HasCheckConstraint("ck_sale_items_product_name", "btrim(product_name_at_sale) <> ''");

                            t.HasCheckConstraint("ck_sale_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_sale_items_unit_cost", "unit_cost >= 0");

                            t.HasCheckConstraint("ck_sale_items_unit_sale_price", "unit_sale_price >= 0");
                        });
                });

            modelBuilder.Entity("sales_performance_api.Infrastructure.Persistence.Seed.SeedHistory", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.HasKey("Version")
                        .HasName("pk_seed_history");

                    b.ToTable("seed_history", "public");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Product", b =>
                {
                    b.HasOne("sales_performance_api.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Sale", b =>
                {
                    b.HasOne("sales_performance_api.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_customers");

                    b.HasOne("sales_performance_api.Domain.Entities.Manager", "Manager")
                        .WithMany("Sales")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_managers");

                    b.Navigation("Customer");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("sales_performance_api.Domain.Entities.Category", "CategoryAtSale")
                        .WithMany("SaleItems")
                        .HasForeignKey("CategoryIdAtSale")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_categories");

                    b.HasOne("sales_performance_api.Domain.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_products");

                    b.HasOne("sales_performance_api.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sale_items_sales");

                    b.Navigation("CategoryAtSale");

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Manager", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("sales_performance_api.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
